/**
 * The RTK Query cache tags for this package's services.
 *
 * They belong here for the same reason the permission codes do: they name THIS
 * package's resources. RTK refuses any tag the base api has not declared, so a
 * host spreads these into its own tagTypes rather than transcribing them - a
 * transcription that falls behind is a cache that silently stops invalidating.
 */

export const FINANCE_TAG_TYPES = [
  "Branches",
  "FinanceAccounts",
  "FinanceAuditLog",
  "FinanceBankAccounts",
  "FinanceBankDocuments",
  "FinanceBudgets",
  "FinanceConcessions",
  "FinanceCreditNotes",
  "FinanceCreditTransfers",
  "FinanceCustomers",
  "FinanceDeferredIncome",
  "FinanceDeliveries",
  "FinanceDeposits",
  "FinanceDunning",
  "FinanceEntities",
  "FinanceExpenseClaims",
  "FinanceFeeAssignments",
  "FinanceFeeStructures",
  "FinanceFixedAssets",
  "FinanceInterBranch",
  "FinanceInvoices",
  "FinanceJournals",
  "FinancePayerLinks",
  "FinancePayerPayments",
  "FinancePaymentPlans",
  "FinancePayments",
  "FinancePayroll",
  "FinancePeriods",
  "FinancePettyCash",
  "FinanceProvisions",
  "FinanceRefunds",
  "FinanceReports",
  "FinanceSettings",
  "FinanceSetup",
  "FinanceStatementLines",
  "FinanceStatutory",
  "FinanceTax",
  "FinanceWriteOffs",
  "INVOICE",
  "ImportBatches",
  "NONE",
  "PaymentsCollections",
  "PaymentsCustody",
  "PaymentsHeldChecks",
  "PaymentsHeldSettlements",
  "PaymentsPayoutBatches",
  "PaymentsPayouts",
  "PaymentsTransactions",
  "PaymentsVirtualAccounts",
  "PaymentsWebhooks",
  "ProcCatalog",
  "ProcCategories",
  "ProcContracts",
  "ProcGoodsReceipts",
  "ProcPurchaseOrders",
  "ProcQuotations",
  "ProcRequisitions",
  "ProcRfqs",
  "ProcSettings",
  "ProcStock",
  "ProcStockLocations",
  "ProcVendorAssessments",
  "ProcVendorCreditNotes",
  "ProcVendorInvoices",
  "ProcVendorPayments",
  "ProcVendors",
  "QUOTED",
  "WorkflowInstances",
  "WorkflowPending",
  "WorkflowSubmissions",
  "WorkflowTeamLoad",
] as const;

export type FinanceTagType = (typeof FINANCE_TAG_TYPES)[number];
