/** Short page-title explanations shared by every Finance destination. */
export const FINANCE_HELP = {
  dashboard: "A summary of cash, collections, receivables, spending and items that need attention.",
  ledger: "Review every posted accounting entry and create or follow manual journals.",
  entities: "Manage separate sets of books, each with its own accounts, periods and document numbers.",
  accounts: "Manage the accounts used to classify assets, liabilities, equity, income and expenses.",
  periods: "Control which accounting months are open, closed or permanently locked.",
  currencies: "Maintain currencies and exchange rates used to convert transactions into the entity's base currency.",
  "tax-codes": "Define tax rates and the accounts affected when tax is charged or withheld.",
  "cost-centers": "Group income and spending by department or branch for reporting.",
  dimensions: "Add reporting categories such as projects, funds or programmes.",
  "tax-tables": "Maintain national PAYE bands, states and pension administrators used by payroll.",
  customers: "Manage the people and organisations being billed, including their balances and statements.",
  "fee-structures": "Create reusable billing templates that determine what customers are charged.",
  invoices: "Create and track amounts customers owe.",
  receipts: "Record money received and apply it to one or more outstanding invoices.",
  "payer-payments": "Split one parent's or sponsor's payment across several customers they pay for.",
  deposits: "Track refundable money held for customers until it is returned or forfeited.",
  "credit-transfers": "Move unused credit from one customer to another after approval.",
  "credit-notes": "Reduce or increase an already-issued customer balance.",
  refunds: "Return customer credit or recognise an amount that will not be collected.",
  concessions: "Record approved discounts, scholarships and fee waivers.",
  "payment-plans": "Divide an outstanding balance into scheduled instalments.",
  dunning: "Manage overdue reminders and follow-up policies.",
  provisions: "Estimate the portion of older debts that may not be collected.",
  "deferred-income": "Release fees billed in advance into income during the periods they belong to.",
  banking: "Manage bank accounts, import statements and review their book balances.",
  "bank-reconciliation": "Match bank statement lines with entries in the ledger and explain differences.",
  claims: "Review and reimburse approved spending paid personally by staff.",
  "petty-cash": "Manage petty-cash funds, vouchers, replenishments and returns.",
  payroll: "Calculate, post and pay staff salaries and statutory deductions.",
  budgets: "Compare planned income and spending with actual results.",
  assets: "Track asset purchases, depreciation, disposals and current book values.",
  tax: "Prepare, file and pay tax obligations.",
  "inter-branch-transfers": "Record money and other value transferred or requested between branches.",
  "held-receipts": "Track money one branch collected for invoices belonging to another branch.",
  "inter-branch-balances": "Show what each pair of branches owes one another.",
  recharges: "Share a cost paid by one branch with the other branches that benefited.",
  "shared-cost-rules": "Define whether shared costs are absorbed or recharged and how they are divided.",
  gateway: "Track online checkout payments and whether the payment provider confirmed them.",
  "virtual-accounts": "Manage customer bank accounts that identify and reconcile transfers automatically.",
  payouts: "Send individual payments to approved recipients.",
  batches: "Combine several payouts and submit them together.",
  settlement: "Match provider payouts with the bank and record the corresponding settlement entries.",
  "held-settlements": "Track online payments held by the platform before they are paid to each branch.",
  "held-reconciliations": "Compare held-money records with the payment provider's records each day.",
  transactions: "Review every collection, payout and transfer that moved money.",
  "provider-activity": "Review every request sent to the payment provider, including refused and failed requests.",
  webhooks: "Investigate provider events that could not be processed into the system or books.",
  "trial-balance": "Show every account's closing debit or credit and confirm that the ledger balances.",
  "income-statement": "Show income, expenses and the resulting profit or loss for a period.",
  "balance-sheet": "Show assets, liabilities and equity at a selected date.",
  "cash-flow": "Show where cash came from and where it was spent.",
  "changes-in-equity": "Explain how each equity balance moved during the period.",
  "statutory-pack": "Produce the annual financial statements needed for statutory reporting.",
  analytics: "Analyse posted activity by cost centre, project, fund or another reporting dimension.",
  seals: "Confirm that figures from closed periods have not changed.",
  audit: "Review an uneditable record of finance actions, including who acted and what changed.",
  settings: "Configure accounting defaults, calendars, documents, approvals, banking, payroll and receivables policies.",
} as const;
